# Generated by Django 3.1.1 on 2021-02-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210210_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_by_sms',
            field=models.BooleanField(default=False),
        ),
    ]
