# Generated by Django 3.1.1 on 2021-02-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_notify_by_sms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
