# Generated by Django 3.1.1 on 2020-12-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
