# Generated by Django 3.1.1 on 2020-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20201221_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_price',
            field=models.FloatField(),
        ),
    ]
