# Generated by Django 3.1.1 on 2020-12-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20201222_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='requested_price',
            field=models.FloatField(default=0),
        ),
    ]
