# Generated by Django 3.1.1 on 2020-12-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20201223_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
