# Generated by Django 3.1.1 on 2021-01-30 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210130_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='item_image_url',
        ),
    ]
