# Generated by Django 3.1.1 on 2021-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_item_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
